title: Izzati Nurvira
email: izzatinurvira3126@gmail.com
description: > # this means to ignore newlines until "baseurl:"
i am from Sigli.
I am currently living in the dormitory of the Lhokseumawe State Polytechnic.
My hobbies are cooking and singing.
Date of Birth: May 31 2007
I am currently studying at Lhokseumawe State Polytechnic,
Department of Information and Computer Technology,
Informatics Engineering Study Program, Class 1C.

url: https://izzati31.github.io

plugins:
 -jekyll-feed
 -jekyll-sitemap
 -jekyll-seo-tag